- name: Install IIS Server
  hosts: windows_servers  # Specify the target group of Windows servers
  gather_facts: no        # Skip gathering facts if not required (useful for faster execution)
  collections:
    - community.windows

  tasks:
    - name: Install IIS feature
      win_feature:
        name: Web-Server     # This is the IIS Web Server role
        state: present       # Ensure IIS is installed

    - name: Start IIS service
      win_service:
        name: W3Svc          # The IIS service that manages the web server
        state: started       # Ensure the IIS service is started
        start_mode: auto     # Set it to start automatically on boot
    
    - name: Allow HTTP traffic on port 80
      community.windows.win_firewall_rule:
        name: "Allow HTTP traffic"
        enable: yes
        localport: 3001
        protocol: TCP
        action: allow
        direction: in

    - name: Ensure the directory exists
      win_file:
        path: C:\virtualdirectory\nir
        state: directory

    - name: Create a sample index.html file
      copy:
        content: |
          <html>
            <head><title>Nir New Website</title></head>
            <body><h1>Welcome to Nir New Website</h1></body>
          </html>
        dest: "C:\\virtualdirectory\\nir\\index.html"

    - name: Create the IIS website
      community.windows.win_iis_website:
        name: "NirNewWebsite"
        state: "started"
        port: 3001
        application_pool: "DefaultAppPool"
        physical_path: "C:\\virtualdirectory\\nir"
        bindings: "http/*:3001"

